#!/usr/bin/python3
import random
number = random.randint(-10, 10)
for i in range(-10,10):
    if i == 0:
    print(i"is zero")
    if i < 0:
    print(i"is negative")
    if i > 0:
    print(i"is positive")
    